<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShgV12X\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShgV12X/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerShgV12X.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerShgV12X\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerShgV12X\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ShgV12X',
    'container.build_id' => '91e79356',
    'container.build_time' => 1526373846,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerShgV12X');
